### why numpy is required


In [2]:
# As a part of data science, machine learning and deep learning, it is very common requirement to perform complex mathematical operation as given below
# 1.creation of Array and Matrices
# 2.perform several operation on Array and Matrices
# 3.perform integral calculas operation
# 4.sloving differntial equation
# 4.Statitic realted operation

# To perform a complex opeartion an in-built library is not present in core python.


### what are the features of numpy

In [3]:
# Numpy is superfast as it is written in python
# Numpy acts as a backbone for various data science libraray  like pandas, scikit-learn etc.
# pandas internelly use nd-array(numpy core data structure) to store data in dataframes
# numpy has vectarization features which improves performance while iterating elements    

### what is nd-array ?

In [7]:
# nd-array is numpy data structure which is used to hold data
# nd-array -> N-Dimensional Array or NumpyArray
# This data structure is most commmenly used in data scince library like pandas, scikit-learn etc.
# nd-array is index collection of homogeneous elements.
# numpy library contains lots of function to create nd-array
# 1-D array is knows as Vector.
# 2-D array is knows as Matrix.

### topics covered as part of numpy course

In [6]:
# creation of numpy array
# Array Operation
# Array Attributes
# Array Indexing and Slicing
# Brodcasting
# Iterating Over Array
# Binary Condition
# Copy and View Operation
# Sort and Search
# Statistics Related function
# Linear Algebra Functions

### similarities b/w python list and numpy array

In [8]:
# Both can be used to store data
# The order is preserved in both type, hence we can use index to access data
# Slicing is also applicable for both
# Both are mutable, i.e once we create list or Array we can change its elements.

### Differnces b/w Python List and Numpy Array

In [20]:
# list is inbuilt data type but numpy array is not
# List can hold hetrogeneous elements but numpy array can hold only homogeneous elements
# colors = ["black", "blue", 1234, 678, 'C'], arr = np.array([1,2,3,4,5])
# On Array, vector operations can be performed (Operation which can be performed on every element of array), same can't be done for list elements.
# Array consumes less memory when compared with python list.
# Array are superfast in comparision with List

### Examples of vector operations

In [14]:
import numpy as np
a = np.array([10,20,30,40])
b = [10,20,30,40]
a

array([10, 20, 30, 40])

In [10]:
type(a)

numpy.ndarray

In [11]:
a+1

array([11, 21, 31, 41])

In [12]:
a*2

array([20, 40, 60, 80])

In [13]:
a/2

array([ 5., 10., 15., 20.])

In [15]:
b+1

TypeError: can only concatenate list (not "int") to list

In [16]:
b*2

[10, 20, 30, 40, 10, 20, 30, 40]

### Examples of size comparisions

In [19]:
import sys
a = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140, 150])
b= [10,20,30,40,50,60,70,80,90,100,110,120,130,140, 150]
print(sys.getsizeof(a))
print(sys.getsizeof(b))

172
176
